Before 2022/Code_Buffer/PycharmProjects/LfLearning/LfLearning/urls.py
# _*_ encoding:utf-8 _*_
"""LfLearning URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
import xadmin
from django.views.static import serve

from users.views import LoginView, LogoutView
from users.views import RegisterView
from users.views import ActiveUserView
from users.views import ForgetPasswordView
from users.views import ResetView
from users.views import ModifyPwdView
from users.views import IndexView

from LfLearning.settings import MEDIA_ROOT

urlpatterns = [
    # 用户
    url(r'^xadmin/', xadmin.site.urls),
    url('^$', IndexView.as_view(), name="index"),
    url('^login/$', LoginView.as_view(), name="login"),
    url('^logout/$', LogoutView.as_view(), name="logout"),
    url('^register/$', RegisterView.as_view(), name="register"),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$', ActiveUserView.as_view(), name="user_active"),
    url(r'^forget/$', ForgetPasswordView.as_view(), name="forget_pwd"),
    url(r'^reset/(?P<active_code>.*)/$', ResetView.as_view(), name="reset_pwd"),
    url(r'^modify_pwd/$', ModifyPwdView.as_view(), name="modify_pwd"),
    # 机构url配置
    url(r'^org/', include('organization.urls', namespace="org")),
    # 课程url配置
    url(r'^course/', include('courses.urls', namespace="course")),
    # 上传文件访问（图片）
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    # 用户个人中心
    url(r'^users/', include('users.urls', namespace="users")),
]

Before 2022/Code_Buffer/PycharmProjects/LfLearning/apps/courses/urls.py
# _*_ encoding:utf-8 _*_
__author__ = 'lifan'
__date__ = '2017/3/19 下午1:28'

from django.conf.urls import url
from .views import CourseListView, CourseDetailView, CourseChapterView, CourseCommentView, AddCommentView,ViewPlayView

urlpatterns = [
    url(r'^list/$', CourseListView.as_view(), name="course_list"),
    url(r'^detail/(?P<course_id>\d+)/$', CourseDetailView.as_view(), name="course_detail"),
    url(r'^chapter/(?P<course_id>\d+)/$', CourseChapterView.as_view(), name="course_info"),
    url(r'^comment/(?P<course_id>\d+)/$', CourseCommentView.as_view(), name="course_comment"),
    url(r'^add_comment/$', AddCommentView.as_view(), name="add_comment"),
    url(r'^video_play/(?P<video_id>\d+)/$', ViewPlayView.as_view(), name="video_play"),
]

Before 2022/Code_Buffer/PycharmProjects/LfLearning/apps/organization/urls.py
# _*_ encoding:utf-8 _*_
__author__ = 'lifan'
__date__ = '2017/3/13 下午8:55'

from django.conf.urls import url
from organization.views import OrgView, OrgHomeView, OrgCourseView, OrgDescView, OrgTeacherView
from organization.views import AddFavView
from organization.views import TeacherListView, TeacherDetailView

urlpatterns = [
    # 所有机构
    url(r'^list/$', OrgView.as_view(), name="org_list"),
    # 机构模块
    url(r'^home/(?P<org_id>\d+)/$', OrgHomeView.as_view(), name="org_home"),
    url(r'^course/(?P<org_id>\d+)/$', OrgCourseView.as_view(), name="org_course"),
    url(r'^desc/(?P<org_id>\d+)/$', OrgDescView.as_view(), name="org_desc"),
    url(r'^org_teacher/(?P<org_id>\d+)/$', OrgTeacherView.as_view(), name="org_teacher"),
    # 收藏功能
    url(r'^org_fav/$', AddFavView.as_view(), name="add_fav"),
    # 教师相关模块
    url(r'^teacher/list/$', TeacherListView.as_view(), name="teacher_list"),
    url(r'^teacher/detail/(?P<teacher_id>\d+)/$', TeacherDetailView.as_view(), name="teacher_detail"),
]

Before 2022/Code_Buffer/PycharmProjects/LfLearning/apps/users/urls.py
# _*_ encoding:utf-8 _*_
__author__ = 'lifan'
__date__ = '2017/3/24 下午2:29'

from django.conf.urls import url
from .views import UserInfoView, ImageUploadView, UpdatePwdView, MyCourseView
from .views import MyFavOrgView, MyFavTeacherView, MyFavCourseView

urlpatterns = [
    url(r'^info/$', UserInfoView.as_view(), name="user_info"),
    # 头像
    url(r'^image/upload/$', ImageUploadView.as_view(), name="image_upload"),
    url(r'^update/password/$', UpdatePwdView.as_view(), name="update_pwd"),
    url(r'^my_course/$', MyCourseView.as_view(), name="my_course"),
    url(r'^fav_org/$', MyFavOrgView.as_view(), name="fav_org"),
    url(r'^fav_teacher/$', MyFavTeacherView.as_view(), name="fav_teacher"),
    url(r'^fav_course/$', MyFavCourseView.as_view(), name="fav_course"),
]

Before 2022/Code_Buffer/PycharmProjects/LfLearning/apps/courses/models.py
# _*_ encoding:utf-8 _*_
from __future__ import unicode_literals
from datetime import datetime

from django.db import models
from organization.models import CourseOrg, Teacher


# Create your models here.


class Course(models.Model):
    course_org = models.ForeignKey(CourseOrg, verbose_name=u"课程机构", null=True, blank=True)
    teacher = models.ForeignKey(Teacher, verbose_name=u"授课讲师", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u"课程名")
    desc = models.CharField(max_length=300, verbose_name=u"课程描述")
    detail = models.TextField(verbose_name=u"课程详情")
    degree = models.CharField(verbose_name=u"难度", choices=(("cj", "初级"), ("zj", "中级"), ("gj", "高级")), max_length=2)
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    category = models.CharField(max_length=20, verbose_name=u"所属类别", default=u"计算机")
    image = models.ImageField(upload_to="courses/%Y/%m", verbose_name=u"封面图", max_length=100)
    click_nums = models.IntegerField(default=0, verbose_name=u"点击数")
    tag = models.CharField(default='', verbose_name=u"标签", max_length=10)
    is_banner = models.BooleanField(verbose_name=u"轮播", default=False)
    pre_learning = models.CharField(max_length=300, verbose_name=u"课程须知", default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程"
        verbose_name_plural = verbose_name

    def get_zhangjie_nums(self):
        return self.lesson_set.all().count()

    def get_learning_student(self):
        return self.usercourse_set.all()[:6]

    def get_lesson(self):
        return self.lesson_set.all()

    def __unicode__(self):
        return self.name


class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"章节名")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"章节"
        verbose_name_plural = verbose_name

    def get_video(self):
        return self.video_set.all()

    def __unicode__(self):
        return self.name


class Video(models.Model):
    lesson = models.ForeignKey(Lesson, verbose_name=u"章节")
    name = models.CharField(max_length=100, verbose_name=u"视频名")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    url = models.CharField(max_length=200, verbose_name=u"视频地址", default="")
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"视频"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name


class CourseResource(models.Model):
    course = models.ForeignKey(Course, verbose_name=u"课程")
    name = models.CharField(max_length=100, verbose_name=u"名称")
    download = models.FileField(upload_to="course/resource/%Y/%m", verbose_name=u"资源文件", max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u"添加时间")

    class Meta:
        verbose_name = u"课程资源"
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.name

Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/active_fail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<p>链接失效</p>
</body>
</html>

Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/course-comment.html
{% extends 'base.html' %}

{% block title %}课程评论(LF-Learning){% endblock %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
	<link rel="stylesheet" type="text/css" href="/static/css/muke/course/course-comment.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css">
{% endblock %}

{% block bread %}
<section>
    <div class="wp">
        <div class="crumbs">
            <ul>
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
                <li><a href="{% url 'course:course_detail' course.id %}">课程详情</a>></li>
                <li>课程评论</li>
            </ul>
        </div>
    </div>
</section>
{% endblock %}

{% block content %}
<div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 6px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">&nbsp;&nbsp;{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value"><strong>大约{{ course.learn_times }}分钟</strong></span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.students }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">
    <div class="info-bar clearfix">
    <div class="content-wrap clearfix">
    <div class="content">
    <div class="mod-tab-menu">
        <ul class="course-menu clearfix">
            <li><a class="" id="learnOn" href="{% url 'course:course_info' course.id %}"><span>章节</span></a></li>
            <li><a id="commentOn" class="ui-tabs-active active" href="{% url 'course:course_comment' course.id %}"><span>评论</span></a></li>
        </ul>
    </div>

    <!--发布评论-->
    <div id="js-pub-container" class="issques clearfix js-form">
        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
            <textarea id="js-pl-textarea" class="" placeholder="喜欢这个课程吗？给我们一些评论！" ></textarea>
        </div>
        <input type="button" id="js-pl-submit" class="pub-btn" data-cid="452" value="发表评论">
        <p class="global-errortip js-global-error"></p>
    </div>
    <div id="course_note">
        <ul class="mod-post" id="comment-list">
        {% for course_comments in comments %}
            <li class="post-row">
                <div class="media">
                    <span target="_blank"><img src='{{ MEDIA_URL }}{{ course_comments.user.image }}' width='40' height='40' /></span>
                </div>
                <div class="bd">
                    <div class="tit">
                        <span target="_blank">{{ course_comments.user.username }}</span>
                    </div>
                    <p class="cnt">{{ course_comments.comments }}</p>
                    <div class="footer clearfix">
                        <span title="创建时间" class="l timeago">时间：{{ course_comments.add_time }}</span>
                    </div>
                </div>
            </li>
        {% endfor %}
        </ul>
    </div>
    </div>

    <div class="aside r">
    <div class="bd">
    <div class="box mb40">
        <h4>资料下载</h4>
        <ul class="downlist">
            {% for courses_res in resources %}
                <li>
                    <span><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ courses_res.name }}</span>
                    <a href="{{ MEDIA_URL }}{{ courses_res.download }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                </li>
            {% endfor %}
        </ul>
    </div>

    </div>
    </div>
    </div>
    </div>
    </div>
</div>
{% endblock %}

{% block custom_js %}

<script type="text/javascript">
    $('#js-pl-submit').on('click', function(){
        var comments = $("#js-pl-textarea").val()
        if(comments == ""){
            alert("评论不能为空")
            return
        }
        $.ajax({
            cache: false,
            type: "POST",
            url:"{% url 'course:add_comment' %}",
            data:{'course_id':{{ course.id }}, 'comments':comments},
            async: true,
            beforeSend:function(xhr, settings){
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function(data) {
                if(data.status == 'fail'){
                    if(data.msg == '用户未登录'){
                        window.location.href="{% url 'login' %}";
                    }else{
                        alert(data.msg)
                    }
                }else if(data.status == 'success'){
                    window.location.reload();//刷新当前页面.
                }
            },
        });
    });
</script>
{% endblock %}

Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/index.html
{% extends 'base.html' %}
{% block title %}课程机构列表(LF-Learning){% endblock %}
{% block bread %}
{% endblock %}

{% block custom_js %}
    <script type="text/javascript" src="/static/js/index.js"></script>
{% endblock %}

{% block content %}
    <div class="banner">
        <div class="wp">
            <div class="fl">
                <div class="imgslide">
                    <ul class="imgs">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.url }}">
                                    <img width="1200" height="478" src="{{ MEDIA_URL }}{{ banner.image }}"/>
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
                <div class="unslider-arrow prev"></div>
                <div class="unslider-arrow next"></div>
            </div>
        </div>
    </div>
    <section>
        <div class="wp">
            <ul class="feature">
                <li class="feature1">
                    <img class="pic" src="/static/images/f1.png"/>
                    <p class="center">专业权威</p>
                </li>
                <li class="feature2">
                    <img class="pic" src="/static/images/f2.png"/>
                    <p class="center">课程最新</p>
                </li>
                <li class="feature3">
                    <img class="pic" src="/static/images/f3.png"/>
                    <p class="center">名师授课</p>
                </li>
                <li class="feature4">
                    <img class="pic" src="/static/images/f4.png"/>
                    <p class="center">数据真实</p>
                </li>
            </ul>
        </div>
    </section>
{#    <section>#}
{#        <div class="module">#}
{#            <div class="wp">#}
{#                <h1>核心课程</h1>#}
{#                <div class="module1 eachmod">#}
{#                    <div class="module1_1 left">#}
{#                        <img width="220" height="635" src="/static/images/m1_2.jpg"/>#}
{#                        <p class="fisrt_word"><br/><br/><br/>最新课程<br/>名师授课</p>#}
{#                        <a class="more" href="{% url 'course:course_list' %}">查看更多课程 ></a>#}
{#                    </div>#}
{#                    <div class="right group_list">#}
{#                        {% for course in courses %}#}
{#                            <div class="module1_8 box">#}
{#                                <a href="{% url 'course:course_detail' course.id %}">#}
{#                                    <img width="225" height="190"#}
{#                                         src="{{ MEDIA_URL }}{{ course.image }}"/>#}
{#                                </a>#}
{#                                <div class="des">#}
{#                                    <a href="{% url 'course:course_detail' course.id %}">#}
{#                                        <h2 title="{{ course.name }}">{{ course.name }}</h2>#}
{#                                    </a>#}
{#                                    <span class="fl">难度：<i class="key">{{ course.get_degree_display }}</i></span>#}
{#                                    <span class="fr">学习人数：{{ course.students }}</span>#}
{#                                </div>#}
{#                                <div class="bottom">#}
{#                                    <span class="fl"#}
{#                                          title="{{ course.course_org.name }}">{{ course.course_org.name }}</span>#}
{#                                    <span class="star fr">{{ course.fav_nums }}</span>#}
{#                                </div>#}
{#                            </div>#}
{#                        {% endfor %}#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{#    <section>#}
{#        <div class="module">#}
{#            <div class="wp">#}
{#                <h1>平台机构</h1>#}
{#                <div class="module3 eachmod">#}
{#                    <div class="module3_1 left">#}
{#                        <img width="220" height="470" src="/static/images/m1_1.jpg"/>#}
{#                        <p class="fisrt_word">名校来袭<br/>权威认证</p>#}
{#                        <a class="more" href="{% url 'org:org_list' %}">查看更多机构 ></a>#}
{#                    </div>#}
{#                    <div class="right">#}
{#                        <ul>#}
{#                            {% for org_show in org %}#}
{#                                <li class="{% if forloop.counter|divisibleby:5 %}five{% endif %}">#}
{#                                    <a href="{% url 'org:org_home' org_show.id %}">#}
{#                                        <div class="company">#}
{#                                            <img width="185" height="100" src="{{ MEDIA_URL }}{{ org_show.image }}"/>#}
{#                                            <div class="score">#}
{#                                                <div class="circle">#}
{#                                                    <h2>{{ org_show.get_category_display }}</h2>#}
{#                                                </div>#}
{#                                            </div>#}
{#                                        </div>#}
{#                                        <p><span class="key" title="{{ org_show.name }}">{{ org_show.name }}</span></p>#}
{#                                    </a>#}
{#                                </li>#}
{#                            {% endfor %}#}
{#                        </ul>#}
{#                    </div>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{% endblock %}

Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/org-detail-desc.html
{% extends 'org_base.html' %}
{% block title %}机构介绍页（LF-Learning）{% endblock %}
{% block page_path %}机构介绍{% endblock %}
{% block right_form %}
    <div class="right companycenter layout" >
        <div class="head">
            <h1>机构介绍</h1>
        </div>
        <div class="des">
            <p><p>&nbsp; &nbsp;</p><h1 class="ue_t" label="Title center" name="tc" style="border-bottom-color:#cccccc;border-bottom-width:2px;border-bottom-style:solid;padding:0px 4px 0px 0px;text-align:center;margin:0px 0px 20px;"><span style="color:#c0504d;">关于我们</span></h1>
            {{ course_org.desc }}
        </div>
    </div>
{% endblock %}



Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/org_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <title>{% block title %}{% endblock %}机构首页(LF-Learning)</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/animate.css">
    <link rel="stylesheet" type="text/css" href="/static/css/style.css">
    <link rel="stylesheet" type="text/css" href="/static/js/plugins/queryCity/css/cityLayout.css">
    {% block custom_css %}{% endblock %}
    <script src="/static/js/jquery.min.js" type="text/javascript"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
    {% block custom_js %}{% endblock %}
</head>

<body>
<section class="headerwrap headerwrap2">
    <header>
        <div class="header2 header">
            {% if request.user.is_authenticated %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p><b>LF-Learning在线教育平台</b></p></div>
                        <div class="personal">
                            <dl class="user fr">
                                <dd>lifan<img class="down fr" src="/static/images/top_down.png"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                </dt>
                            </dl>
                            <div class="userdetail">
                                <dl>
                                    <dt><img width="80" height="80"
                                             src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                                    </dt>
                                    <dd>
                                        <h2>欢迎用户：</h2>
                                        <p>{{ request.user.username }}</p>
                                    </dd>
                                </dl>
                                <div class="btn">
                                    <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
                                    <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% else %}
                <div class="top">
                    <div class="wp">
                        <div class="fl"><p><b>LF-Learning在线教育平台</b></p></div>
                        <a style="color:white" class="fr registerbtn" href="{% url 'register' %}">注册</a>
                        <a style="color:white" class="fr loginbtn" href="/login/">登录</a>
                    </div>
                </div>
            {% endif %}

            <div class="middle companyheader">
                <div class="wp">
                    <img class="fl" style="width: 160px;height: 105px" src="{{ MEDIA_URL }}{{ course_org.image }}"/>
                    <div class="head fl">
                        <h1>
                            {{ course_org.name }}
                            <img src="/static/images/authentication.png"/>
                            <img src="/static/images/gold.png"/>
                        </h1>
                        <p class="fl">
                            <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                            <span class="precision company-credit" data-star-scope="5.0"></span>
                            <span class="key">5.0</span>
                        </p>
                    </div>
                    <div class="btn fr collectionbtn notlogin" data-favid="22" data-fav-type="1">
                        {% if has_fav %}已经收藏{% else %}收藏{% endif %}
                    </div>
                </div>
            </div>
        </div>
    </header>
</section>

<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'org:org_list' %}">课程机构</a>></li>
            <li>{% block page_path %}机构首页{% endblock %}</li>
        </ul>
    </div>
</section>

<section>
    <div class="wp list personal_list comp">
        <div class="left">
            <ul>
                <li class="{% ifequal current 'home' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_home' course_org.id %}">机构首页</a></li>
                <li class="{% ifequal current 'course' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_course' course_org.id %}">拥有课程</a></li>
                <li class="{% ifequal current 'teacher' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_teacher' course_org.id %}">拥有讲师</a></li>
                <li class="{% ifequal current 'desc' %}active2{% endifequal %}"><a
                        href="{% url 'org:org_desc' course_org.id %}">关于机构</a></li>
            </ul>
        </div>
        {% block right_form %}
        {% endblock %}
</section>

<footer>
    <div class="footer">
        <div class="wp">
            <ul class="cont">
                <li class="logo"><a href=""><img src="/static/images/lflogo.png"/></a></li>
                <li class="code"><img src="/static/images/code.png"/>
                    <p class="center">扫描获取联系</p></li>
                <li class="third"><img class="fl" src="/static/images/tell.png"/>
                    <p class="tell">13058917751</p>
                    <p class="time">周一至周日 9:00-18:00</p></li>
            </ul>
        </div>
        <p class="line"></p>
        <div class="wp clear">
            <span class="fl">&nbsp;&nbsp;浙江师范大学 数理与信息工程学院 软件工程(中外合作)专业 毕业设计</span>
            <span class="fr">设计者：李 凡 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;2016年12月-2017年5月</span>
        </div>
    </div>
</footer>

<section>
    <ul class="sidebar">
        <li class="totop"></li>
    </ul>
</section>
</div>

<script src="/static/js/selectUi.js" type='text/javascript'></script>
<script type="text/javascript" src="/static/js/plugins/laydate/laydate.js"></script>
<script src="/static/js/plugins/layer/layer.js"></script>
<script src="/static/js/plugins/queryCity/js/public.js" type="text/javascript"></script>
<script src="/static/js/plugins/jquery.scrollLoading.js" type="text/javascript"></script>
<script src="/static/js/deco-common.js" type="text/javascript"></script>
<script type="text/javascript" src="/static/js/plugins/jquery.raty.js"></script>
<script type="text/javascript">

    //收藏分享
    function add_fav(current_elem, fav_id, fav_type) {
        $.ajax({
            cache: false,
            type: "POST",
            url: "{% url 'org:add_fav' %}",
            data: {'fav_id': fav_id, 'fav_type': fav_type},
            async: true,
            beforeSend: function (xhr, settings) {
                xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
            },
            success: function (data) {
                if (data.status == 'fail') {
                    if (data.msg == '用户未登录') {
                        window.location.href = "/login/";
                    } else {
                        current_elem.text(data.msg)
                    }
                } else if (data.status == 'success') {
                    current_elem.text(data.msg)
                }
            },
        });
    }
    $('.collectionbtn').on('click', function () {
        add_fav($(this), {{ course_org.id }}, 2);
    });

</script>

</body>
</html>

Before 2022/Code_Buffer/PycharmProjects/LfLearning/templates/usercenter-fav-course.html
{% extends 'usercenter_base.html' %}
{% block title %}我的收藏（LF-Learning）{% endblock %}
{% block bread %}
<section>
    <div class="wp">
        <ul class="crumbs">
            <li><a href="{% url 'index' %}">首页</a>></li>
            <li><a href="{% url 'users:user_info' %}">个人中心</a>></li>
            <li>我的收藏</li>
        </ul>
    </div>
</section>
{% endblock %}
{% block content %}
<div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li ><a href="{% url 'users:fav_org' %}">收藏机构</a> </li>
                        <li><a href="{% url 'users:fav_teacher' %}">收藏教师 </a> </li>
                        <li class="active"><a href="{% url 'users:fav_course' %}">收藏课程</a> </li>
                    </ul>
                </div>
                 <div class="companycenter">
                    <div class="group_list brief">
                    {% for course in course_list %}
                     <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="215" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="{% url 'course:course_detail' course.id %}"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.students }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                     {% endfor %}
                    </div>
                </div>
            </div>
        </div>
{% endblock %}


